<!DOCTYPE html>
<html>
<head>
	<title>Rest'Oran</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- ~ ~ CSS & JS Vendor ~ ~ -->
	<link rel="stylesheet" href="public/css/normalize.css">
	<link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lemon" rel="stylesheet"> 
	
	<!-- ~ ~ CSS & JS Personnal ~ ~ -->
	<link rel="stylesheet" type="text/css" media="screen" href="public/css/main.css" />
	<script src="public/js/main.js"></script>
	
</head>
<body>

	<?php require('apps/header.php'); ?>
	<?php require('apps/content.php'); ?>
	<?php require('apps/footer.php'); ?>
	
</body>
</html>