<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script|Playfair+Display">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="css/normalize.css">
		<link rel="stylesheet" href="public/css/style.css">

	<title>BLOF f1</title>
</head>
<body>

	<?php require('apps/header.php'); ?>
	<!-- header.phtml -->
	<?php require('apps/content.php'); ?>  <!--  le point après $page fait la concaténation
	<!-- home.phtml OU contact.phtml -->
	<?php require('apps/footer.php'); ?>
	<!-- footer.phtml -->
	
</body>
</html>