<h2>Livraison</h2>
<form method="POST" id="delivery">
	<input type="hidden" name="action" value="delivery">
	<div class="flex"> 
		<div>
			<table>
				<thead>
					<tr>
						<th>Produits</th>
						<th>Prix Unitaire</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($products as $product) : ?>
					<tr>
						<td><?php echo $product->getName(); ?></td>
						<td><?php echo $product->getPrice(); ?> €</td>
						<td><!-- <input type="text" name="commande[<?=$product->getId()?>]"> -->
							<select name="commande[<?=$product->getId()?>]">
								<option>-</option>
       							<option>1</option>
						        <option>2</option>
						        <option>3</option>
						        <option>4</option>
						        <option>5</option>
						        <option>6</option>
						        <option>7</option>
						        <option>8</option>
						        <option>9</option>
						        <option>10</option>
						        <!-- <option>11</option>
						        <option>12</option>
						        <option>13</option>
						        <option>14</option>
						        <option>15</option>
						        <option>16</option>
						        <option>17</option>
						        <option>18</option>
						        <option>19</option>
						        <option>20</option>
 -->							</select>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<div>
			<fieldset>
				<legend>Coordonnées</legend>
				<label for="name">Nom :</label><input type="text" name="customer_name" placeholder="Votre nom" id="name">
				<label for="tel">Tél :</label><input type="text" name="customer_tel" placeholder="Votre numéro de téléphone" id="tel">
				<label for="address">Adresse :</label><input type="text" name="customer_address" placeholder="Votre adresse" id="address">
				<label for="city">Ville :</label><input type="text" name="customer_city" placeholder="Votre ville" id="city">
			</fieldset>
			<fieldset>
				<label for="comment">Commentaire :</label><textarea id="comment" placeholder="Un commentaire ?" name="comments"></textarea>
			</fieldset>
			<fieldset>
				<legend>Livraison</legend>
				<label for="date">Date et heure de livraison :</label>
				<select name="date">
					<?php foreach ($dates as $date) echo '<option>'.$date.'</option>';?>
				</select>
			</fieldset>
			<br><br><br>
			<br><br><br>
			<button type="submit">Faites vous livrez ! </button>
		</div>
	</div>
</form>