<footer>
	<section>
		<article>
			<h3>Menu</h3>
			<nav>
				<a href="index.php">Accueil</a>
				<a href="index.php">La Carte</a>
				<a href="index.php">Réservation</a>
				<a href="index.php">Commande</a>
			</nav>
		</article>
		<article>
			<h3>Information pratique</h3>
			<address>99 Avenue des Champs-Elysées<br>75008 Paris<br>01 40 69 60 50</address>
		</article>
		<article>
			<h3>Connexion</h3>
			<form action="index.php" class="form-control">
				<input type="text" name="login" id="" placeholder="Utilisateur">
				<input type="text" name="password" id="" placeholder="Mot de passe">
				<button type="submit">Login</button>
			</form>
		</article>
	</section>
</footer>
