<form method="POST" id="comments">
	<input type="hidden" name="action" value="createcomments">

	<fieldset>
		<legend>Laissez un commentaire</legend>
		<label for="name">Nom : </label><input type="text" name="author" placeholder="Votre nom" id="author"><br><br>
		<label for="email">Email: </label><input type="text" name="email" placeholder="Votre email" id="email"><br>
		<label for="note">Note de 0 à 5 : </label><input type="number" min="0" max="5" name="note" placeholder="Note sur 5">		
		<textarea name="content" id="content" placeholder="Laissez votre commentaire... "></textarea>
		<button type="submit">Poster votre commentaire</button>
	</fieldset>
</form>


